# Generated by Django 3.1.6 on 2021-02-05 16:05

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_krikurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krikurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_url, shortner.validators.validate_url_com]),
        ),
    ]
