# Generated by Django 3.1.6 on 2021-02-21 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailnotifications', '0003_auto_20210220_1500'),
        ('shortner', '0006_auto_20210205_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='krikurl',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emailnotifications.useremails'),
            preserve_default=False,
        ),
    ]
