# Generated by Django 3.1.6 on 2021-02-24 16:03

from django.db import migrations, models
import emailnotifications.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userEmails',
            fields=[
                ('email_ID', models.EmailField(max_length=254, unique=True, validators=[emailnotifications.validators.validate_Email])),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
