# Generated by Django 3.1.6 on 2021-02-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userEmails',
            fields=[
                ('email_ID', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
