# Generated by Django 3.1.6 on 2021-02-20 14:59

from django.db import migrations, models
import emailnotifications.validators


class Migration(migrations.Migration):

    dependencies = [
        ('emailnotifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useremails',
            name='email_ID',
            field=models.EmailField(default='nihar@gmail.com', max_length=254, unique=True, validators=[emailnotifications.validators.validate_Email]),
        ),
    ]
