# Generated by Django 3.1.6 on 2021-02-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailnotifications', '0003_auto_20210220_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
